repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.
  name: name-x
  description: description-x
  topics: topic-x, topic-y, topic-z

labels:
  - name: wip
    color: A83944
    description: Used to block in progress PRs from being merged.
  - name: maintenance
    color: 6BA890
    description: General repo maintenance / configuration
  - name: documentation
    color: C9C086
    description: Documentation changes
  - name: ci
    color: E8A4BC
    description: Changes related to automation
  - name: infrastructure
    color: F4B7F4
    description: Changes made to project infrastructure

  - name: two
    color: CEDAE5
    description: box two
  - name: sum
    color: B7CEE5
    description: box sum
