name: Dispatch Test

on:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo hello
