name: Continuous Integration

on:
  - push

jobs:
  ###########################################################################
  #
  # ███████╗██╗██╗     ███████╗    ██████╗ ███████╗██╗      █████╗ ████████╗███████╗██████╗
  # ██╔════╝██║██║     ██╔════╝    ██╔══██╗██╔════╝██║     ██╔══██╗╚══██╔══╝██╔════╝██╔══██╗
  # █████╗  ██║██║     █████╗      ██████╔╝█████╗  ██║     ███████║   ██║   █████╗  ██║  ██║
  # ██╔══╝  ██║██║     ██╔══╝      ██╔══██╗██╔══╝  ██║     ██╔══██║   ██║   ██╔══╝  ██║  ██║
  # ██║     ██║███████╗███████╗    ██║  ██║███████╗███████╗██║  ██║   ██║   ███████╗██████╔╝
  # ╚═╝     ╚═╝╚══════╝╚══════╝    ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═════╝
  #
  #################################################################
  # file-lint:
  #   name: General File Lint
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       command:
  #         - cr
  #         - crlf
  #         - trailing-newline
  #         - trailing-single-newline
  #         - trailing-space
  #         - utf8
  #         - utf8-bom
  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: dogmatic69/actions/file/lint/awesome-ci@master
  #       with:
  #         command: file-${{ matrix.command }}

  # makefile-lint:
  #   name: Makefile Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: dogmatic69/actions/file/lint/checkmake@master

  # file-done:
  #   name: Done
  #   runs-on: ubuntu-latest
  #   needs: [file-lint, makefile-lint]
  #   steps:
  #     - run: true

  # #############################################################################
  # #
  # #  ██████╗ ██╗████████╗    ██████╗ ███████╗██╗      █████╗ ████████╗███████╗██████╗
  # # ██╔════╝ ██║╚══██╔══╝    ██╔══██╗██╔════╝██║     ██╔══██╗╚══██╔══╝██╔════╝██╔══██╗
  # # ██║  ███╗██║   ██║       ██████╔╝█████╗  ██║     ███████║   ██║   █████╗  ██║  ██║
  # # ██║   ██║██║   ██║       ██╔══██╗██╔══╝  ██║     ██╔══██║   ██║   ██╔══╝  ██║  ██║
  # # ╚██████╔╝██║   ██║       ██║  ██║███████╗███████╗██║  ██║   ██║   ███████╗██████╔╝
  # #  ╚═════╝ ╚═╝   ╚═╝       ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═════╝
  # #
  # #############################################################################
  # git-lint:
  #   name: Git Lint
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       command:
  #         - conflicts
  #         - ignored
  #   steps:
  #     - uses: actions/checkout@master
  #       with:
  #         fetch-depth: 0
  #     - uses: dogmatic69/actions/git/lint/awesome-ci@master
  #       with:
  #         command: git-${{ matrix.command }}

  # gitleaks:
  #   name: GitLeaks
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #       with:
  #         fetch-depth: 0
  #     - uses: dogmatic69/actions/git/audit/gitleaks@master

  # git-done:
  #   name: Done
  #   runs-on: ubuntu-latest
  #   needs: [git-lint, gitleaks]
  #   steps:
  #     - run: true

  # #############################################################################
  # #
  # # ██████╗  ██████╗  ██████╗██╗  ██╗███████╗██████╗     ██████╗ ███████╗██╗      █████╗ ████████╗███████╗██████╗
  # # ██╔══██╗██╔═══██╗██╔════╝██║ ██╔╝██╔════╝██╔══██╗    ██╔══██╗██╔════╝██║     ██╔══██╗╚══██╔══╝██╔════╝██╔══██╗
  # # ██║  ██║██║   ██║██║     █████╔╝ █████╗  ██████╔╝    ██████╔╝█████╗  ██║     ███████║   ██║   █████╗  ██║  ██║
  # # ██║  ██║██║   ██║██║     ██╔═██╗ ██╔══╝  ██╔══██╗    ██╔══██╗██╔══╝  ██║     ██╔══██║   ██║   ██╔══╝  ██║  ██║
  # # ██████╔╝╚██████╔╝╚██████╗██║  ██╗███████╗██║  ██║    ██║  ██║███████╗███████╗██║  ██║   ██║   ███████╗██████╔╝
  # # ╚═════╝  ╚═════╝  ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝    ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═════╝
  # #
  # #############################################################################

  # audit-trivy:
  #   name: Trivy Scan
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       image:
  #         - box-sum
  #         - box-two
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: build
  #       run: docker build -t ${{ matrix.image }} ./${{ matrix.image }}
  #     - uses: dogmatic69/actions/docker/audit/trivy@master
  #       with:
  #         image: ${{ matrix.image }}
  #         path: ./${{ matrix.image }}

  # lint-hadolint:
  #   name: Hadolint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: dogmatic69/actions/docker/lint/hadolint@master

  # docker-done:
  #   name: Done
  #   runs-on: ubuntu-latest
  #   needs: [audit-trivy, lint-hadolint]
  #   steps:
  #     - run: true

  #############################################################################
  #
  # ██████╗ ██████╗  ██████╗      ██╗███████╗ ██████╗████████╗
  # ██╔══██╗██╔══██╗██╔═══██╗     ██║██╔════╝██╔════╝╚══██╔══╝
  # ██████╔╝██████╔╝██║   ██║     ██║█████╗  ██║        ██║
  # ██╔═══╝ ██╔══██╗██║   ██║██   ██║██╔══╝  ██║        ██║
  # ██║     ██║  ██║╚██████╔╝╚█████╔╝███████╗╚██████╗   ██║
  # ╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚════╝ ╚══════╝ ╚═════╝   ╚═╝
  #
  #############################################################################
  project-checks:
    name: Project Specific Checks
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     image:
    #       - box-sum
    #       - box-two
    steps:
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"

      - name: echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - name: list files
        run: |
          URL="https://api.github.com/repos/ahmed91abbas/${GITHUB_REPOSITORY}/pulls/11/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          echo $FILES
      # - uses: actions/checkout@master
      # - name: Lint
      #   run: make -C ${{ matrix.image }} lint
      # - name: Test
      #   run: make -C ${{ matrix.image }} test

  # project-done:
  #   name: Done
  #   runs-on: ubuntu-latest
  #   needs: [project-checks]
  #   steps:
  #     - run: true
# URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
# URL="https://api.github.com/repos/ahmed91abbas/ci-test/pulls/11/files"