name: Continuous Integration

on:
  - pull_request

jobs:
  project-checks:
    name: Project Specific Checks
    runs-on: ubuntu-latest
    steps:
      - name: list changed boxes
        id: changed_boxes
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          regex="(box-[0-9a-z]*)"
          for f in $FILES
          do
              if [[ $f =~ $regex ]]
              then
                  name="${BASH_REMATCH[1]}"
                  result=$result" "$name
              fi
          done
          echo $result
          echo "::set-output name=boxes::$result"
      - uses: actions/checkout@master
      - name: Lint
        run: |
          for box in ${{steps.changed_boxes.outputs.boxes}}
          do
            make -C $box lint
          done
      - name: Test
        run: |
          for box in ${{steps.changed_boxes.outputs.boxes}}
          do
            make -C $box test
          done
